# S2Net Configuration File

# Model configuration
model:
  input_dim: 3
  hidden_dim: 256
  latent_dim: 128
  num_points: 1024
  num_lstm_layers: 2
  num_pyramid_levels: 3
  use_temporal_variational: true
  use_multi_scale: true
  use_uncertainty: true
  dropout: 0.1

# Training configuration
training:
  epochs: 100
  batch_size: 8
  learning_rate: 1e-4
  weight_decay: 1e-5
  kl_weight: 1.0
  reconstruction_weight: 1.0
  temporal_weight: 0.1
  uncertainty_weight: 0.1
  gradient_clip_norm: 1.0

# Data configuration
data:
  dataset: 'synthetic'  # 'kitti', 'nuscenes', 'synthetic'
  data_path: 'data/'
  sequence_length: 10
  prediction_length: 5
  num_points: 1024
  num_workers: 4
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1

# Optimizer configuration
optimizer:
  type: 'adam'
  lr: 1e-4
  weight_decay: 1e-5
  betas: [0.9, 0.999]

# Scheduler configuration
scheduler:
  type: 'reduce_on_plateau'  # 'step', 'cosine', 'reduce_on_plateau'
  step_size: 30
  gamma: 0.1
  T_max: 100
  eta_min: 1e-6
  factor: 0.5
  patience: 10

# Loss configuration
loss:
  use_emd: false
  use_temporal: true
  use_uncertainty: false

# Data augmentation
augmentation:
  rotation_range: [-0.785, 0.785]  # [-π/4, π/4] radians
  translation_range: [-0.5, 0.5]
  scaling_range: [0.9, 1.1]
  noise_std: 0.005
  dropout_prob: 0.05

# Evaluation configuration
evaluation:
  num_samples: 10
  save_predictions: true
  save_visualizations: true

# System configuration
system:
  device: 'cuda'
  seed: 42
  validate_every: 10
  save_every: 20
  log_every: 10

# Paths
paths:
  save_dir: 'checkpoints/'
  log_dir: 'logs/'
  output_dir: 'evaluation_results/'
